### ISSUE TITLE
Attaching to QEMU-CHERI only works if the ELF binary has OS_ABI_FREEBSD

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/gdb#12]
At least this is the case on Linux where it will attempt to instantiate a linux target (without the CHERI bits)
if the OSABI is NONE.

**Comment by bsdjhb** [comment]
Yes, the CHERI support is split a bit between mips-tdep.c and mips-fbsd-tdep.c and it is only fully enabled for a CheriBSD binary.  Moving more of the CHERI bits over to mips-tdep.c would permit it to to be used for non-FreeBSD binaries.  I do think it might instantiate the register info for a non-FreeBSD binary that has the right bits set in the ELF header though in e_flags.  Also, the registers should be advertised by qemu to a remote debugger always.  Do you have more details on what breaks?

**Comment by arichardson** [comment]
```
File: /tmp/test.exe
Format: ELF64-mips
Arch: cheri
AddressSize: 64bit
LoadName: 
ElfHeader {
  Ident {
    Magic: (7F 45 4C 46)
    Class: 64-bit (0x2)
    DataEncoding: BigEndian (0x2)
    FileVersion: 1
    OS/ABI: SystemV (0x0)
    ABIVersion: 0
    Unused: (00 00 00 00 00 00 00)
  }
  Type: Executable (0x2)
  Machine: EM_MIPS (0x8)
  Version: 1
  Entry: 0xFFFFFFFF80020134
  ProgramHeaderOffset: 0x40
  SectionHeaderOffset: 0xA3E48
  Flags [ (0x30C1C005)
    EF_MIPS_ABI_CHERIABI (0xC000)
    EF_MIPS_ARCH_4 (0x30000000)
    EF_MIPS_CPIC (0x4)
    EF_MIPS_MACH_CHERI128 (0xC10000)
    EF_MIPS_NOREORDER (0x1)
  ]
  HeaderSize: 64
  ProgramHeaderEntrySize: 56
  ProgramHeaderCount: 4
  SectionHeaderEntrySize: 64
  SectionHeaderCount: 29
  StringTableSectionIndex: 27
}
```
QEMU command:
```
/local/scratch/alr48/cheri/output/sdk/bin/qemu-system-cheri128 -M malta -m 128m -nographic -kernel /tmp/test.exe -append 'HELLO WORLD' -s -S
```

GDB output
```
$CHERI_SDK/gdb -ex="target remote :1234" /tmp/test.exe
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /tmp/test.exe...done.
Remote debugging using :1234
/local/scratch/alr48/cheri/gdb/gdb/mips-linux-tdep.c:1748: internal-error: void mips_linux_init_abi(struct gdbarch_info, struct gdbarch *): Assertion `gdbarch_num_regs (gdbarch) <= MIPS_RESTART_REGNUM' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) 
```

**Comment by arichardson** [comment]
Whereas with a freebsd osabi I get this:
```
$CHERI_SDK/gdb -ex="target remote :1234" /tmp/test.exe
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /tmp/test.exe...done.
Remote debugging using :1234
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) starti
The "remote" target does not support "run".  Try "help target" or "continue".
(gdb) stepi
0x0000000000000000 in ?? ()
Cannot access memory at address 0x0
(gdb) stepi
0x0000000000000000 in ?? ()
Cannot access memory at address 0x0
(gdb) stepi
0x0000000000000000 in ?? ()
Cannot access memory at address 0x0
(gdb) stepi
0x0000000000000000 in ?? ()
Cannot access memory at address 0x0
(gdb) step
Cannot find bounds of current function
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0xffffffff800017fc in ?? ()
(gdb) bt
warning: GDB can't find the start of the function at 0xffffffff800017fc.

    GDB is unable to find the start of the function at 0xffffffff800017fc
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0xffffffff800017fc for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
#0  0xffffffff800017fc in ?? ()
```
```
File: /tmp/test.exe
Format: ELF64-mips
Arch: cheri
AddressSize: 64bit
LoadName: 
ElfHeader {
  Ident {
    Magic: (7F 45 4C 46)
    Class: 64-bit (0x2)
    DataEncoding: BigEndian (0x2)
    FileVersion: 1
    OS/ABI: FreeBSD (0x9)
    ABIVersion: 0
    Unused: (00 00 00 00 00 00 00)
  }
  Type: Executable (0x2)
  Machine: EM_MIPS (0x8)
  Version: 1
  Entry: 0xFFFFFFFF80020134
  ProgramHeaderOffset: 0x40
  SectionHeaderOffset: 0xA3E48
  Flags [ (0x30C1C005)
    EF_MIPS_ABI_CHERIABI (0xC000)
    EF_MIPS_ARCH_4 (0x30000000)
    EF_MIPS_CPIC (0x4)
    EF_MIPS_MACH_CHERI128 (0xC10000)
    EF_MIPS_NOREORDER (0x1)
  ]
  HeaderSize: 64
  ProgramHeaderEntrySize: 56
  ProgramHeaderCount: 4
  SectionHeaderEntrySize: 64
  SectionHeaderCount: 29
  StringTableSectionIndex: 27
}
```

**Comment by bsdjhb** [comment]
Oof, so it's only Linux binaries that break and it needs changes in mips-linux-tdep.c (since it's an assertion in the Linux-specific MIPS backend).  (A bare metal CHERI binary wouldn't run into that.)

**Comment by bsdjhb** [comment]
Hmm, so I think the fact that GDB thinks your bare metal binary is a Linux binary is a root issue.  One thing to check is if you have a ".note.ABI-tag" section with a "GNU" note.  However, if you don't have that, probably gdb is just falling back to the Linux osabi as the compiled-in default osabi (assuming you are running the gdb binary on a Linux host).  'show osabi' will show you what the default osabi is.  You can do 'set osabi none' to tell GDB not to fallback to its default but to instead assume a bare metal binary before invoking 'target remote'.   One way to clear GDB's notion of a "default" OSABI is to explicitly use 'mips64-unknown-elf' as the target option to ./configure when building the binary for Linux (for the native CHERI binary we probably want a default OSABI).

**Comment by bsdjhb** [comment]
I've moved a lot more bits over to mips-tdep.c along with adding the CHERI ABIs as MIPS ABIs, so I think this is probably fixed now, but it would be good to test again at some point.
