### ISSUE TITLE
Backtraces broken in latest libunwind master

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/gdb#26]
For some reason GDB is trying to use the current stack pointer as the previous frame address:
(when built without libunwind assertions)
```
#0  _nanosleep () at _nanosleep.S:3
#1  0x000000000021ca70 in initScanProlog (enc=0x40f4b250 [rwRW,0x40f4b250-0x40f4b360],
    ptr=0x40ad6000 [rwRW,0x40ad6000-0x40ad6800] "\n", end=0x40ad6001 [rwRW,0x40ad6000-0x40ad6800] "",
    nextTokPtr=0x7fffffd6c0 [rwRW,0x7fffffd6c0-0x7fffffd6d0])
    at /Users/alex/cheri/cheribsd/contrib/expat/lib/xmltok_ns.c:70
#2  0x0000007fffffd6c0 in ?? ()
```

Register dump of the crash: 
```
Trapframe Register Dump:
$0: 0                  at: 0x1                v0: 0x1                v1: 0x2
a0: 0                  a1: 0x4                a2: 0                  a3: 0x1
a4: 0x1                a5: 0x14               a6: 0x2                a7: 0x3333333333333333
t0: 0                  t1: 0x101010101010101  t2: 0x1                t3: 0
s0: 0                  s1: 0x70               s2: 0xfffffffffffdffff s3: 0
s4: 0x3d               s5: 0xffd7             s6: 0x48               s7: 0x8000000000000000
t8: 0x524e0            t9: 0x70               k0: 0                  k1: 0
gp: 0x1aa0             sp: 0xffffffff84039125 s8: 0                  ra: 0x4
status: 0x408084b3 mullo: 0; mulhi: 0; badvaddr: 0x136cf92d4
cause: 0x48; pc: 0x11b5c0
BadInstr: 0xd8220011 clc	c1,zero,272(c2)
CHERI cause: ExcCode: 0x01 RegNum: $c02 (length violation)
$ddc: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c01: v:1 s:0 p:0007817d b:000000000025cac0 l:0000000000000070 o:0 t:-1
$c02: v:1 s:0 p:0004817d b:0000000040f4b250 l:0000000000000110 o:0 t:-1
$c03: v:1 s:0 p:0006817d b:0000000040ad6000 l:0000000000000800 o:0 t:-1
$c04: v:1 s:0 p:0006817d b:0000000040ad6000 l:0000000000000800 o:1 t:-1
$c05: v:1 s:0 p:0007817d b:0000007fffffd6c0 l:0000000000000010 o:0 t:-1
$c06: v:1 s:0 p:0007817d b:0000007fffffd6c0 l:0000000000000010 o:0 t:-1
$c07: v:1 s:0 p:0007817d b:0000007fffffd520 l:0000000000000010 o:0 t:-1
$c08: v:1 s:0 p:0007817d b:0000007fffffd740 l:0000000000000010 o:0 t:-1
$c09: v:1 s:0 p:0007817d b:0000007fffffd730 l:0000000000000010 o:0 t:-1
$c10: v:1 s:0 p:0007817d b:0000007fffffd720 l:0000000000000010 o:0 t:-1
$c11: v:1 s:0 p:0007817d b:0000007fff7ff000 l:00000000007ff7e0 o:7fe510 t:-1
$c12: v:1 s:0 p:00068117 b:0000000000120000 l:0000000000169130 o:11b550 t:-1
$c13: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c14: v:1 s:0 p:0007817d b:0000007fffffdbcc l:0000000000000004 o:0 t:-1
$c15: v:1 s:0 p:0007817d b:0000007fffffdbb0 l:0000000000000010 o:0 t:-1
$c16: v:1 s:0 p:0007817d b:0000007fffffdba0 l:0000000000000010 o:0 t:-1
$c17: v:1 s:0 p:00068117 b:0000000000120000 l:0000000000169130 o:fca70 t:-1
$c18: v:1 s:0 p:0007817d b:000000000025fe99 l:0000000000000026 o:0 t:-1
$c19: v:1 s:0 p:0006817d b:0000000040ad6000 l:0000000000000800 o:0 t:-1
$c20: v:1 s:0 p:0006817d b:0000000040ad6000 l:0000000000000800 o:1 t:-1
$c21: v:1 s:0 p:0007817d b:000000000025cac0 l:0000000000000070 o:0 t:-1
$c22: v:1 s:0 p:0007817d b:000000000025cac0 l:0000000000000070 o:0 t:-1
$c23: v:1 s:0 p:00068117 b:0000000000120000 l:0000000000169130 o:15c330 t:-1
$c24: v:1 s:0 p:0007817d b:0000007fff7ff000 l:00000000007ff7e0 o:7fe510 t:-1
$c25: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c26: v:1 s:0 p:00078115 b:00000000407cfa00 l:00000000000150f0 o:0 t:-1
$pcc: v:1 s:0 p:00068117 b:0000000000120000 l:0000000000169130 o:11b5c0 t:-1
```

With libunwind assertions on I get the following:

`Assertion failed: (lastReg >= (int)cieInfo.returnAddressRegister && "register range does not contain return address register"), function stepWithDwarf, file /Users/alex/cheri/cheribsd/contrib/subrepo-cheri-libunwind/src/DwarfInstructions.hpp, line 219.`

**Comment by arichardson** [comment]
This might be caused by gdb trying to use the MIPS register info for unwinding?

#define _LIBUNWIND_HIGHEST_DWARF_REGISTER_MIPS      65
#define _LIBUNWIND_HIGHEST_DWARF_REGISTER_MIPS_CHERI 103

**Comment by arichardson** [comment]
Never mind. This was a bug in LLVM which would cause the DWARF info for MIPS binaries to emit C17 as the return register.
